version: 0.0
os: linux

files:
  - source: build/libs/
    destination: /home/ubuntu/app/deploy/build/libs
    overwrite: yes
  - source: deploy.sh
    destination: /home/ubuntu/app/deploy
    overwrite: yes

permissions:
  - object: /home/ubuntu/app/deploy
    owner: ubuntu
    group: ubuntu

hooks:
  AfterInstall:
    - location: deploy.sh
      timeout: 60
      runas: ubuntu
