version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/app/deploy
    overwrite: yes

permissions:
  - object: /home/ubuntu//opt/codedeploy-agent/deployment-root/360ceed4-d76d-48aa-a43b-e2258c185bf0/d-3KR2T23IA/deployment-archive/build/libs
    owner: ubuntu
    group: ubuntu
hooks:
  AfterInstall:
    - location: deploy.sh
      timeout: 60
      runas: ubuntu
